### ISSUE TITLE
[Feature request] Physics tick, onBegin, onDestroy for Plugin API

### ISSUE THREAD

**Issue by trsh** [MissingDeadlines/iolite#11]
We could have a separate physics tick, that ticks at same time as engine physics tick to do physics stuff before rendering.

**Comment by trsh** [comment]
Also we could have onBeing event- when game mode is started and before anything else to allocate some resources, and onDestroy event when game mode is exited to release those, etc.

**Comment by begla** [comment]
Regarding `onBegin` and `onDestroy`,I've added the following for the next iteration:

https://github.com/MissingDeadlines/iolite/blob/38f0fa56e2652f3b26c90ec6aa2c5775a812dc7b/iolite_c_api/iolite_api.h#L929
https://github.com/MissingDeadlines/iolite/blob/38f0fa56e2652f3b26c90ec6aa2c5775a812dc7b/iolite_c_api/iolite_api.h#L931
https://github.com/MissingDeadlines/iolite/blob/38f0fa56e2652f3b26c90ec6aa2c5775a812dc7b/iolite_c_api/iolite_api.h#L964
https://github.com/MissingDeadlines/iolite/blob/38f0fa56e2652f3b26c90ec6aa2c5775a812dc7b/iolite_c_api/iolite_api.h#L966

**Comment by begla** [comment]
Feel free to reopen this if there's a need for additional callbacks instead of handling the stepping/interpolation manually.
