### ISSUE TITLE
[Feature request] Enhancements for particles 

### ISSUE THREAD

**Issue by trsh** [MissingDeadlines/iolite#18]
Editor:

Bounciness and drag factor for particles
The eye in UI, for hiding, currently doesn't work for particle effect

API:

From discord discussion: `The interface is a little barebones at the moment. I will expose all the available functionality`

**Comment by begla** [comment]
> The eye in UI, for hiding, currently doesn't work for particle effect

This is fixed in `v0.4.0-beta10`.

**Comment by begla** [comment]
@trsh `v0.4.0-beta13` adds support for *linear* and *collision damping coefficients*.
