### ISSUE TITLE
[Feature request] Proper scaling on HiDPI displays

### ISSUE THREAD

**Issue by f1nniboy** [MissingDeadlines/iolite#20]
![Bildschirmfoto vom 2023-10-18 13-07-32](https://github.com/MissingDeadlines/iolite/assets/55994155/446953a7-be68-4945-a099-2924b17b64ac)
The editor currently looks like this on my 3440x1440 display, and the text is a bit too small to work comfortably with it. A scaling/font size option in the settings would be great.

**Comment by begla** [comment]
@f1nniboy You could give the `editor_ui_scale` setting a shot with a value `> 1.0` in the `settings.json` file in the root directory or the user's documents folder on Windows.

**Comment by begla** [comment]
@f1nniboy I've just pushed `v0.4.0-beta10`. You can now tweak this value during runtime via the editor settings dialog.
