### ISSUE TITLE
[Feature request] Add search for shape selector 

### ISSUE THREAD

**Issue by trsh** [MissingDeadlines/iolite#27]
When I have a lot of vox's, the scroll can get really large and sensitive and its hard to find shapes.

**Comment by trsh** [comment]
![image](https://github.com/MissingDeadlines/iolite/assets/3727523/3f26c482-8d5a-40c4-a181-6e321bb01ba4)

**Comment by begla** [comment]
Available in `v0.5.0-beta8`.
