### ISSUE TITLE
Saving world does not save paletteName assignments from editor.

### ISSUE THREAD

**Issue by ascorbius** [MissingDeadlines/iolite#34]
When assigning palettes from the editor (pressing the palette button and choosing a different palette to the one the vox file used) the name of the palette appears in the property window and is shown in the world. 

However, saving the world doesn't appear to save the palette information. 
I tried to save multiple times and checked the contents of the json file but the paletteName properties are empty - they have a "value": "" instead of the "metal" palette I had chosen.
I also tried save world as and checked the contents of that file, no palette values either.

Encountered in pro 0.5.0-beta19

**Comment by begla** [comment]
I gave this a quick spin, and it seems to work as expected on my end. Here's what I did:

1. Execute a minimal installation of the latest beta and wipe the user data directory in `Documents`
2. Launch IOLITE
3. Select the cube in the center and change the palette from "empty" to "chars."
4. Save the world
5. Reload the world

The palette is set to "chars," as expected. I've also restarted the engine and checked the JSON file. Everything is in order.

Could you provide me a similar repro case to find out what is happening?

**Comment by begla** [comment]
Closing. Feel free to reopen if it still occurs!
