### ISSUE TITLE
[Feature request] custom event for Shapes

### ISSUE THREAD

**Issue by trsh** [MissingDeadlines/iolite#43]
`shape_io->disptach_event(shape_ref, "burning", (void*)event_i_data)`

We already have mechanism for getting those, i.e. `on_shape_events `

**Comment by trsh** [comment]
Some sort of filter would also help here, so I don't have to loop over all Shapes that undergo some change. If that can help with performance. If not we handle on our side.

**Comment by begla** [comment]
I would prefer something more generic that is not tied to shapes.

**Comment by begla** [comment]
There's now an interface for custom event streams available in `0.5.0-beta20`. See the C++ sample plugin for a usage sample.
