### ISSUE TITLE
Improve placing entities via the [R] shortcut in the editor

### ISSUE THREAD

**Issue by begla** [MissingDeadlines/iolite#47]
When placing entities via the "R" shortcut in the editor, the ray-cast may hit the shape (or shapes) currently placed.

I suspect this relates to placing hierarchies of entities instead of a single entity with a shape attached, which is currently not handled.

Reported by @Danchyg1337.

**Comment by Danchyg1337** [comment]
Steps to reproduce:
1) On the root node: Attach new entity (With component) -> Character Controller
2) Place it with R on the ground
3) Place it with R on top of any prop that's higher than the ground
4) Repeat from step 2

**Comment by begla** [comment]
Happened due to nodes having bounds with zero extents. Fixed in the latest beta build!
