### ISSUE TITLE
[Feature Request] Setting some component properties isn't viable because of missing type function(Variant plugin\lua_api).

### ISSUE THREAD

**Issue by cosxy** [MissingDeadlines/iolite#50]
"version_string": "v0.4.8" windows

Requesting additional Variant functions for more types.
[Variant](https://docs.iolite-engine.com/en/latest/api/lua.html#Variant.get_string)

trying to set properties for voxelshape or flipbookanimation results in a type mismatch. unable to set variant types in lua since the function don't support type uint8 or type name.

error:
        WARNING (2024-03-24 19:31:46): Variant type mismatch. Expected 'uint8', got 'uint'!
        WARNING (2024-03-24 19:31:46): Variant type mismatch. Expected 'uint8', got 'uint'!
        WARNING (2024-03-24 19:31:46): Variant type mismatch. Expected 'uint8', got 'uint'!

flipbook property information:
        INFO    (2024-03-24 18:09:25): FirstFrame : uint8
        INFO    (2024-03-24 18:09:25): NumFrames : uint8
        INFO    (2024-03-24 18:09:25): CurrentFrame : uint8
        INFO    (2024-03-24 18:09:25): Speed : float

command tried:
        FlipbookAnimation.set_property(char_motion,"FirstFrame",Variant.from_uint8(0))
        FlipbookAnimation.set_property(char_motion,"NumFrames",Variant.from_uint8(6))
        FlipbookAnimation.set_property(char_motion,"CurrentFrame",Variant.from_uint8(0))
        FlipbookAnimation.set_property(char_motion,"Speed",Variant.from_float(6.0))
        FlipbookAnimation.commit_changes(char_motion)

examples of missing types for voxelshape properities:        
        INFO    (2024-03-24 18:36:11): VoxelShapeName : name
        INFO    (2024-03-24 18:36:11): PaletteName : name
        INFO    (2024-03-24 18:36:11): Flags : uint8
        INFO    (2024-03-24 18:36:11): RigidBodyFlags : uint16
        INFO    (2024-03-24 18:36:11): CollisionGroup : uint8
        INFO    (2024-03-24 18:36:11): CustomSize : u16vec3
        INFO    (2024-03-24 18:36:11): Pivot : vec3
        INFO    (2024-03-24 18:36:11): LinearDamping : float
        INFO    (2024-03-24 18:36:11): AngularDamping : float
        INFO    (2024-03-24 18:36:11): Density : float
        INFO    (2024-03-24 18:36:11): DepenetrationVelocityFactor : float
        INFO    (2024-03-24 18:36:11): NumPositionIterations : uint
        INFO    (2024-03-24 18:36:11): NumVelocityIterations : uint
        INFO    (2024-03-24 18:36:11): FractureType : uint8
        INFO    (2024-03-24 18:36:11): MaxNumConvexSubdivisions : uint8
        
Requesting variant.from_uint8() function.
setting uint for uint8 causes application to crash.

**Comment by begla** [comment]
Comment available in #51.
