### ISSUE TITLE
[Feature request] API function to set parent for node

### ISSUE THREAD

**Issue by trsh** [MissingDeadlines/iolite#52]
It should have an option `keep_transforms`, what means, that new transforms will be calculated, so the parented child node stays exactly the same. We could also add `keep_transforms` to `create_with_parent`.

**Comment by begla** [comment]
That's a great suggestion; I'll add that. It's already internally available and not exposed via the API.

**Comment by begla** [comment]
I've added a new "attach" function to the node interface (which can be used to reattach an existing node) and extended the existing "create_with_parent" function. Both support the new "ignore_parent" parameter, which keeps the current transform without considering (and undoing) the parent transform.

This will be available in the next build. 👍
