### ISSUE TITLE
IOLITE does not open when I try to open it

### ISSUE THREAD

**Issue by GhostYT4** [MissingDeadlines/iolite#56]
When I try to open IOLITE nothing happens. It would be appreciated if there is a fix to this. Thanks

**Comment by begla** [comment]
Try updating your GPU and chipset driver.

If this does not help, please post some information on your setup. Otherwise, it is hard to guess what is going wrong. The operating system, CPU, and GPU are most important.

**Comment by begla** [comment]
Please feel free to reopen this if you need any more help.
