### ISSUE TITLE
Is there a demo available for reference, and is there a corresponding tutorial; I now find that I cannot exit after entering game mode

### ISSUE THREAD

**Issue by dd123-a** [MissingDeadlines/iolite#65]

**Comment by begla** [comment]
Check this repository; there are many samples available. You can open the editor by pressing `F3`. Closing this, questions like this better fit our Discord server!

**Comment by dd123-a** [comment]
> Check this repository; there are many samples available. You can open the editor by pressing `F3`. Closing this, questions like this better fit our Discord server!

In game mode, how to try out scene examples? I tried moving the mouse and keyboard, but there was no response. I am sorry that I am unable to join Discore due to network issues
