### ISSUE TITLE
Hot reload not reporting script being updated

### ISSUE THREAD

**Issue by trsh** [MissingDeadlines/iolite#7]
Reproduction steps:

1) Download iolite-v0.1.21
2) Download sample projects
3) Copy over sample projects and add to app_metadata.json `data_sources`
4) Run the editor and open, for example, 'sample_physics' world
5) Open script 'iolite-v0.1.21\sample_physics\media\scripts\gameplay_physics.lua
6) Open console F2
7) Change script
8) Nothing show up in console
9) Run game and the changes have no effect
10) Run game second time and the changes have effect

OS: Windows 11 x64

**Comment by trsh** [comment]
Yes, my `active_data_source` was not set right. Sorry. Feel free to close this.

**Comment by begla** [comment]
Improved behavior in v0.2.22.
