### ISSUE TITLE
Integrated graphics causing crash even with graphic Id hint set to main gpu

### ISSUE THREAD

**Issue by VirtualSofia** [MissingDeadlines/iolite#75]
Specs:
CPU: AMD Ryzen 5 3550h with Radeon Vega Mobile Graphics
GPU: Nvidia GeForce GTX 1050

After first installing, Iolite crashed on start up and produced this log
[first_application.log](https://github.com/user-attachments/files/16986915/first_application.log)

After troubleshooting with the discord I disabled the integrated graphics through device manager and launched with no crash or issues producing this log
[second_application.log](https://github.com/user-attachments/files/16986918/second_application.log)
again this had no issue its just here in case it's a useful reference and showing that disabling the integrated graphics fixed the issue 
maybe worth noting is after launching I was able to reenable the integrated graphics and the program continued to run fine, and actually got more FPS (tho I'd assume this is from the integrated graphics picking up background work not Iolite using the integrated graphics)

After as an attempt to a permeant fix I set the graphics ID hint in [settings.json](https://github.com/user-attachments/files/16987011/settings.json) to the ID for the GTX 1050 and and then attempted to launch with integrated graphics enabled and it crashed much like the first crash and produced this log
[third_application.log](https://github.com/user-attachments/files/16987018/third_application.log)

all of those logs were reproduceable, however this is one I was unable to reproduce but it was from as far as I can tell the same setup as the third log but is much longer so may have more details
[cant_reproduce_application.log](https://github.com/user-attachments/files/16987029/cant_reproduce_application.log)

**Comment by begla** [comment]
It seems like the driver of your integrated graphics card is in charge of reporting the list of available physical devices but fails to do so.

Could you try updating the driver of your integrated device and see if it fixes the issue?

**Comment by VirtualSofia** [comment]
That fixed it! Thank you!

**Comment by VirtualSofia** [comment]
It does still require the graphics ID hint, it launches now without but has visual bugs (sample animation scene becomes a red square) and crashes every 3rd play without, which whereas as a dev is not a problem to just add that but could be a problem for players when shipping games so the fix Benjamin on the discord had mentioned("query the supported API level") is probably still a good idea

**Comment by begla** [comment]
Good to hear, and I'm happy to help! 🙂
